#!/bin/bash
set -e

help() {
  printf "Set the environment variable GH_ORG & GH_TEAM

    export GH_ORG={your org}
    export GH_TEAM={target team}

list the names of the users you want to add to the target team

  gh add-team-member member1 member2 member3 ...

"
}

case "$1" in
  --team*|-t*)
    if [[ "$1" != *=* ]]; then shift; fi
    GH_TEAM="${1#*=}"
    shift;
    ;;
  --help|-h)
    help
    exit 0
    ;;
esac

if [ -z "$GH_ORG" ]
then
  GH_ORG=$(gh pwd)
fi

echo "org is $GH_ORG"
echo "team is $GH_TEAM"

for N in "${@}" ;
do
  echo "Adding ${N} to ${GH_TEAM}"
  gh api -X PUT /orgs/$GH_ORG/teams/$GH_TEAM/memberships/${N} -F role='member'
done
