#!/bin/bash
set -e

help() {
  printf "
1. Set the alias:

    cd:                            !gh config set current-org "$1" 2>/dev/null
    pwd:                           !gh config get current-org
   
   Example:
      ✗ gh pwd                   
      ULL-ESIT-DMSI-1920
2. Get the teams:

        ✗ gh org-teams | jq '.name'
        \"all\"
        \"antonella-garcia-alu0101227610\"
        \"casiano-rodriguez-leon-casiano\"
        ...

3. List the names of the users you want to add to the target team

  gh team-add [-t team ] member1 member2 member3 ...

"
}

case "$1" in
  --team*|-t*)
    if [[ "$1" != *=* ]]; then shift; fi
    GITHUB_TEAM="${1#*=}"
    shift;
    ;;
  --help|-h)
    help
    exit 0
    ;;
esac

if [ -z "$GITHUB_ORG" ]
then
  GITHUB_ORG=$(gh pwd)
fi

echo "org is $GITHUB_ORG"
echo "team is $GITHUB_TEAM"

for N in "${@}" ;
do
  echo "Adding ${N} to ${GITHUB_TEAM}"
  gh api -X PUT /orgs/$GITHUB_ORG/teams/$GITHUB_TEAM/memberships/${N} -F role='member'
done
